### ISSUE TITLE
Can you support copying value on double-click?

### ISSUE THREAD

**Issue by wanghongenpin** [Bungeefan/flutter_json#1]
组件非常不错，我现在自己写的，当太大了会卡顿，如果你支持双击value添加事件就用你的了

**Comment by Bungeefan** [comment]
Hi, I took the liberty to translate the title, please try to use English in this repository.

If I understood the translation correctly, you want to be able to copy the value on a double click.
This would require to expose the double-tap event, I will add this, in the meantime you could use the already exposed long-press event to copy the value.

Example usage:
https://github.com/Bungeefan/flutter_debug_overlay/blob/519f76295f7e4aa99aa5dbfa1ca6c14e4686b3e8/lib/src/http_log/item/body_item.dart#L62-L68

**Comment by Bungeefan** [comment]
This is now available in `flutter_json: 0.0.2`.
